### PR TITLE
Added Deadzone Functionality

### LINKED ISSUE #2: Add way to define deadzones / calibrate the analog sticks
Right now we just send the raw data along to XInput, would be nice if we can give the user a way to define their own deadzone though, since not many games allow to customize that.

I'm not sure if calibrating is important, ProconXInput has a method of calibrating ProCon sticks but it seems maybe that's only needed if the controller isn't sending the full 16-bit value that XInput uses (Xbox OG pads do, but Procon only sends an 8-bit value, which is maybe why that needs to be calibrated)

If anyone can think of a good way of implementing those please let me know!

### LINKED ISSUE #12: Is this project still in active development?
I just installed the drivers and stuff, and it really wowed me. It's much better than XBCD, but I just need deadzones, and then it'll be perfect.

### PR DESCRIPTION
**Pull request by skajacore**
Deadzone and adjustment button combination LT + RT + (LS or RS) + DPAD
UP/DN
has been added per controller. Current deadzone is displayed in the
context menu. The deadzone is implemented by mapping the remaining range
of the axis back to the range of 0 to SHRT_MAX. Left and Right analog
sticks can be adjusted individually and is determined by which analog
stick
is pressed down during the deadzone adjustment button combination.

Fixes #2, Fixes #12 

TODO: It would be nice if the deadzone would be remembered by hardware
serial number and stored in the registry or elsewhere.

### CODE REVIEW

**Comment by skajacore** [comment]
image

**Comment by xalender** [comment]
Excellent!, quick question, does this provide deadzone for the triggers as well?, one of my controllers has a right trigger that needs some deadzone to work well, would be great to modify that too.

**Comment by skajacore** [comment]
I had considered it, but mine were right at 0 with no jitter and I wasn't sure if it would really need to be addressed. This would be pretty easy to add in now though. I'll work it up in the branch to add to this pull request.

**Comment by skajacore** [comment]
image

Got the trigger deadzone working! Moved the new context menu items around to make them grouped more logically also.

**Comment by xalender** [comment]
So fast!, great! now the project is awesome, finally i can stop using XOutput and start using a specialized "driver+program". I hope emoose merges those changes and compiles the new version soon as i can't compile it myself (don't have visual studio or fast internet to download it).

I don't know too much how github works but If there's any way for you to post a compiled version while we wait for emoose to actually compile and upload it would be awesome!

**Comment by skajacore** [comment]
Here are the new binaries, you can drop them in your existing install location next to libusb-1.0.dll.

[v1.3.2-deadzone-binaries.zip](https://github.com/emoose/Xb2XInput/files/4672780/v1.3.2-deadzone-binaries.zip)

**Comment by xalender** [comment]
Tested and it worked like a charm! Thank you for your work. Nothing to complain about the deadzone functionality, everything works just fine. As you said it would be good if the deadzones could be remembered (passed as parameters to Xb2XInput maybe?) but apart from that both my controllers are connected and working..

**Comment by emoose** [comment]
Great stuff! Huge apologies for the delay in responding, been away from home/my controllers to test with... gonna take a look at this & #14 now and hopefully get them merged.

Also a while back I did some work on storing settings into an ini file next to XB2X's exe too, after merging these I'll try digging that up and see about adding deadzone stuff into it.

**Pull request merged**
